[package]
name = "esp32-hal"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>", "Arjan Mels <arjan@mels.email>"]
edition = "2018"

[dependencies]
xtensa-lx6-rt = { path = "../xtensa-lx6-rt" }
esp32 = { path = "../esp32"}
nb = "0.1.2"
spin = "0.5.2"
embedded-hal = {version="0.2.3",features = ["unproven"] }

[dev-dependencies]
panic-halt = "0.2.0"
spin = "0.5"

[[example]]
name = "bitbang"

[[example]]
name = "blinky"

[[example]]
name = "button"

[[example]]
name = "hello"

[[example]]
name = "multicore"

[[example]]
name = "rtccntl"

[[example]]
name = "serial"

